In [8]:
import pandas as pd
import  numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df = pd.read_csv('AfricaCupofNationsMatches.csv')

In [10]:
df.head(7)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0

In [4]:
egypt_rows = df[(df.isin(['Egypt']).any(axis=1))]
print(egypt_rows)

    Year      Date  Time    HomeTeam   AwayTeam  HomeTeamGoals  AwayTeamGoals  \
3   1959  22-May-59   NaN      Egypt   Ethiopia            4.0            0.0
5   1959  29-May-59   NaN      Egypt      Sudan            2.0            1.0
7   1962  18-Jan-62   NaN      Egypt     Uganda            2.0            1.0
9   1962  21-Jan-62   NaN  Ethiopia       Egypt            4.0            2.0
13  1963  24-Nov-63   NaN      Egypt    Nigeria            6.0            3.0
14  1963  26-Nov-63   NaN      Egypt      Sudan            2.0            2.0
16  1963  30-Nov-63   NaN      Egypt   Ethiopia            3.0            0.0

                Stage    SpecialWinConditions                 Stadium  \
3    Final Tournament                     NaN   Prince Farouk Stadium
5    Final Tournament                     NaN   Prince Farouk Stadium
7          Semifinals                     NaN  Hailé Sélassié Stadium
9               Final   win after extra time   Hailé Sélassié Stadium
13            Group B                     NaN   Kumasi Sports Stadium
14            Group B                     NaN   Kumasi Sports Stadium
16  Third place match                     NaN    Accra Sports Stadium

            City  Attendance
3          Cairo     30000.0
5          Cairo     30000.0
7    Addis Ababa     30000.0
9    Addis Ababa         NaN
13        Kumasi         NaN
14        Kumasi         NaN
16         Accra         NaN

In [5]:
# counting the number of rows and columns 
df.shape

(622, 12)

In [ ]:
# Rows with missing attendance 
missing_attendance = df[df['Attendance'].isna()]
print(missing_attendance)

     Year                         Date   Time        HomeTeam       AwayTeam  \
1    1957                     10-Feb-57    NaN      Ethiopia    South Africa
8    1962                     20-Jan-62    NaN       Tunisia          Uganda
9    1962                     21-Jan-62    NaN      Ethiopia           Egypt
10   1963                     24-Nov-63    NaN         Ghana         Tunisia
11   1963                     26-Nov-63    NaN         Ghana        Ethiopia
..    ...                           ...    ...            ...            ...
565  2017  29 January 2017 (2017-01-29)  20:00         Egypt         Morocco
566  2017  1 February 2017 (2017-02-01)  20:00  Burkina Faso           Egypt
567  2017  2 February 2017 (2017-02-02)  20:00      Cameroon           Ghana
568  2017  4 February 2017 (2017-02-04)  20:00  Burkina Faso           Ghana
569  2017  5 February 2017 (2017-02-05)  20:00         Egypt        Cameroon

     HomeTeamGoals  AwayTeamGoals                 Stage  \
1              NaN            NaN            Semifinals
8              3.0            0.0     Third place match
9              4.0            2.0                 Final
10             1.0            1.0               Group A
11             2.0            0.0               Group A
..             ...            ...                   ...
565            1.0            0.0        Quarter-finals
566            1.0            1.0           Semi-finals
567            2.0            0.0           Semi-finals
568            1.0            0.0  Third place play-off
569            1.0            2.0                 Final

                                  SpecialWinConditions  \
1    Ethiopia  wins due to disqualification of othe...
8                                                  NaN
9                                win after extra time
10                                                 NaN
11                                                 NaN
..                                                 ...
565                                                NaN
566                        Egypt win on Penalities 3-4
567                                                NaN
568                                                NaN
569                                                NaN

                    Stadium          City  Attendance
1                       NaN           NaN         NaN
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
10     Accra Sports Stadium         Accra         NaN
11     Accra Sports Stadium         Accra         NaN
..                      ...           ...         ...
565    Stade de Port-Gentil   Port-Gentil         NaN
566       Stade de l'Amitié    Libreville         NaN
567    Stade de Franceville   Franceville         NaN
568    Stade de Port-Gentil   Port-Gentil         NaN
569       Stade de l'Amitié    Libreville         NaN

[100 rows x 12 columns]

In [7]:
# select rowss where the home team goals are between 3 and 6 inclusive
home_goals_between_3_and_6 = df[(df['HomeTeamGoals']>=3) & (df['HomeTeamGoals']<=6)]
home_goals_between_3_and_6.head()

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN

In [11]:
# 8. program that changes the 'AwayTeamGoals' in the 3rd row to 10
df.loc[2, 'AwayTeamGoals'] = 10 # locate method
print('changes the AwayTeamGoals in the 3rd row to 10')
print(df.head())

changes the AwayTeamGoals in the 3rd row to 10
   Year      Date  Time    HomeTeam       AwayTeam  HomeTeamGoals  \
0  1957  10-Feb-57   NaN     Sudan           Egypt            1.0
1  1957  10-Feb-57   NaN  Ethiopia    South Africa            NaN
2  1957  16-Feb-57   NaN     Egypt        Ethiopia            4.0
3  1959  22-May-59   NaN      Egypt       Ethiopia            4.0
4  1959  25-May-59   NaN     Sudan        Ethiopia            1.0

   AwayTeamGoals             Stage  \
0            2.0        Semifinals
1            NaN        Semifinals
2           10.0             Final
3            0.0  Final Tournament
4            0.0  Final Tournament

                                SpecialWinConditions                Stadium  \
0                                                NaN      Municipal Stadium
1  Ethiopia  wins due to disqualification of othe...                    NaN
2                                                NaN      Municipal Stadium
3                                                NaN  Prince Farouk Stadium
4                                                NaN  Prince Farouk Stadium

        City  Attendance
0   Khartoum     30000.0
1        NaN         NaN
2   Khartoum     30000.0
3      Cairo     30000.0
4      Cairo     20000.0

In [12]:
#10. Write a Pandas program to get list from DataFrame column headers

column_headers = df.columns.tolist()
print(column_headers)

['Year', 'Date ', 'Time ', 'HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals', 'Stage', 'SpecialWinConditions', 'Stadium', 'City', 'Attendance']